
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: BatchScript@1
  inputs:
    filename: 'power.bat'
    arguments: '3 4'
- task: BatchScript@1
  inputs:
    filename: 'calc.bat'
    arguments: '0 100'